services:

  splunk-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.85.0
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    environment:
      # used by sapm/signalfx exporters
       - SPLUNK_ACCESS_TOKEN
       - SPLUNK_REALM
      # used by splunk_hec exporter
       - SPLUNK_HEC_URL
       - SPLUNK_HEC_TOKEN
    ports:
      - "8888:8888"  # Prometheus metrics exposed by the collector
      - "8889:8889"  # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "55679:55679" # zpages extension
  client:
    build:
      context: ./Example.LogTraceCorrelation.Console
      dockerfile: ../Dockerfile # installs Splunk Distribution of OpenTelemetry .NET Automatic Instrumentation
    entrypoint: "./out/Example.LogTraceCorrelation.Console http://service:5000"
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "Example.LogTraceCorrelation.Console"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://splunk-collector:4318"
      OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES: "Example.LogTraceCorrelation.Console"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=splunk-otel-dotnet-tracing-examples,service.version=1.0.0"
    volumes:
      - ./console-logs:/app/logs
    depends_on:
      service:
        condition: service_healthy
      splunk-collector:
        condition: service_started

  service:
    build:
      context: ./Example.LogTraceCorrelation.Web
      dockerfile: ../Dockerfile # installs Splunk Distribution of OpenTelemetry .NET Automatic Instrumentation
    entrypoint: "./out/Example.LogTraceCorrelation.Web --urls http://*:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/healthz" ]
      # from the docker docs:
      # The health check will first run interval seconds after the container is started, and then again interval seconds after each previous check completes.
      interval: 10s
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "Example.LogTraceCorrelation.Web"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://splunk-collector:4318"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=splunk-otel-dotnet-tracing-examples,service.version=1.0.0"
    volumes:
      - ./web-logs:/app/logs
    depends_on:
      - splunk-collector
